# Generated by Django 4.1 on 2022-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_choice_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="day",
            field=models.CharField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                default="Mon",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="menu", unique_together={("restaurant", "day")},
        ),
        migrations.RemoveField(model_name="menu", name="date",),
    ]
