# Generated by Django 4.1 on 2022-08-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "menu_choice_app",
            "0002_menu_day_alter_menu_unique_together_remove_menu_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "Mon"),
                    ("Tuesday", "Tue"),
                    ("Wednesday", "Wed"),
                    ("Thursday", "Thu"),
                    ("Friday", "Fri"),
                    ("Saturday", "Sat"),
                    ("Sunday", "Sun"),
                ],
                max_length=50,
            ),
        ),
    ]
